### ISSUE TITLE
Allow mpv options with play-with-mpv

### ISSUE THREAD

**Issue by sheychen290** [Thann/play-with-mpv#18]
I use [Send to mpv](https://add0n.com/send-to.html?from=mpv) with firefox and mpv has default media player.

I'm trying to use you addon on vivaldi
With the previous app, i can set arguments ```mpv --title=Player --geometry=45%x45% --load-unsafe-playlists``` to run firefox's mpv with options and keep mpv config clear for other uses.

Make some thing like ```play-with-mpv --title=Player --geometry=45%x45% --load-unsafe-playlists``` should be perfect or maybe ith a config file

**Comment by Thann** [comment]
You can now add MPV args via the extensions options GUI =]
