### ISSUE TITLE
Integrate server.py to the extension?

### ISSUE THREAD

**Issue by sheepdestroyer** [Thann/play-with-mpv#2]
mpv is able to work with any site that youtube-dl supports. Vimeo, Dailymotion, etc should work as well.

edit:
Better tested, does not work on youtube either :/
mpv and youtuble-dl are working on my setup.
This similar extenstion for firefox works great : https://github.com/antoniy/mpv-youtube-dl-binding

edit2:
works after reading the doc... :p 
had to run server.py ; but couldn't that be ran automatically when extention is active and server stoped when disabling the extention or shutting down chrome?

**Comment by ioangogo** [comment]
On you last edit, Yeah, I tried to make a systemd service when I was making my context menu pull request, this is so it would always be in the background, but mpv did not like being run as a systemd service

**Comment by Thann** [comment]
Sorry for taking so long to respond, but it seems you figured out that mpv works with nearly every website thanks to the hard work of the youtube-dl people =]

Unlike Firefox, Chrome's extensions don't allow you to spawn other processes for obvious security reasons, so you need to have some dumb little server like this to spawn them for you. If you're using Firefox I would recommend just using that extension.

As for ststemd, you typically need to set some environment variables to allow the service to work with X11, and it's generally easier to use the FreeDesktop autostart functionality of your DE to start the server =]
