### ISSUE TITLE
Pause youtube video when play with mpv

### ISSUE THREAD

**Issue by tazihad** [Thann/play-with-mpv#37]
It would be good if youtube pause video automatically when open with mpv loads.

**Comment by Haxprox** [comment]
`mpv *.mkv --start=5:00 --pause` - Doesn't it work for you? If so, push "--pause" option to your 'mpv.conf' file'.
Works great for mpv 0.33.0.

**Comment by 3nt3** [comment]
@tazihad what exactly do you mean? The youtube viceo on the youtube web frontend pauses (for me) when requesting it to be started with mpv. The video is started in mpv after it hast loaded. This can be fixed by either changing the server or doing what @Haxprox recommended
