### ISSUE TITLE
facebook videos don't work lately

### ISSUE THREAD

**Issue by cgcgcgcgcg** [Thann/play-with-mpv#38]
I only use play-with-mpv to watch fb & youtube videos, but fb videos don't work today.
I'm using Arch on a slow laptop, right-clicking here:
![ksnip_20201016-224800](https://user-images.githubusercontent.com/38960370/96305818-29fa0a00-1007-11eb-8580-7770a580b5f1.png)

I'm suspecting fb put a lot of junk on their links and this is a youtube-dl issue.

**Comment by Thann** [comment]
I get this error: 
`[ytdl_hook] ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.`

You can try adding arguments in the extension options like `--username=yourusername`, and see if that works.
Also make sure youtube-dl is up to date.
