### ISSUE TITLE
Multiuser solution

### ISSUE THREAD

**Issue by gabrc52** [Thann/play-with-mpv#41]
This setup doesn't play well with multiple users. 

If you set it to autostart on 2 users and:

1. Login into user A
2. Switch user
3. Login into user B
4. `play-with-mpv` can't start on user B because the port is open from user A
5. Click on the extension icon
6. The video will play on user A but we're on account B

**Comment by gabrc52** [comment]
On a second look, the extension already lets you change the port, so only a command line parameter to change the port would be needed, at least for a manual do-it-once setup.

**Comment by Thann** [comment]
Good suggestion!
Implemented in https://github.com/Thann/play-with-mpv/commit/69beabf35d369b8505795abb08b5b924f0ddc198 =]
