### ISSUE TITLE
Shortcut Keybind for playing in mpv

### ISSUE THREAD

**Issue by Cknight70** [Thann/play-with-mpv#46]
Hello, I am a big fan of your extension, but I would much rather prefer to use a keyboard shortcut than to press the extension button. Your readme suggests ctrl+spacebar is the hotkey, but this didn't seem to work for me when I pressed it on a youtube video url.

**Comment by Thann** [comment]
If you look in: chrome://extensions/shortcuts
There should be a "play with mpv" section where you can configure the shortcut.

Let me know if that doesn't fix it for you =]
