### ISSUE TITLE
Debian stores the executable on .local/bin/play-with-mpv

### ISSUE THREAD

**Issue by nyxnor** [Thann/play-with-mpv#48]
On GNU/Linux Debian, the launcher was not set correctly, I had to execute this way `./.local/bin/play-with-mpv`
So I needed to modify the executable to this path.
Changed the Play With MPV (server) on /home/floor/.local/share/applications/ to `Exec=./.local/bin/play-with-mpv` as it is a better consistent solution.
play-with-mpv works on ungoogled-chromium (to appear on search results).

**Comment by Thann** [comment]
You should ensure that `$HOME/.local/bin` is added to your path, so you can just run `play-with-mpv` from anywhere =]
