### ISSUE TITLE
Audio only?

### ISSUE THREAD

**Issue by orschiro** [Thann/play-with-mpv#5]
Hey @Thann love your extension! Question. I want to preserve as much battery of my laptop as I can. Hence want to only stream the audio. Any way to achieve this? :-)

Thanks!

**Comment by Thann** [comment]
Yes!
you can use the keyboard shortcut "minus" to toggle video.
The only problem is this makes the GUI disappear, unless you put the following into: `~/.config/mpv/mpv.conf`
```
force-window=yes
```

That work for you? =]

**Comment by orschiro** [comment]
@Thann awesome! :-D

For me it was `Shift + -`.

Thank you!

**Comment by Thann** [comment]
Great!
I think I'll make `force-window` default so users don't need to edit the config for this =]

**Comment by orschiro** [comment]
> I think I'll make force-window default so users don't need to edit the config for this =]

Great idea! :-)
