### ISSUE TITLE
Best way to launch play-with-mpv?

### ISSUE THREAD

**Issue by orschiro** [Thann/play-with-mpv#6]
Hey @Thann,

I have a question about:

> Start server by running play-with-mpv (or use the Linux free desktop shortcut)

The way I do it at the moment is opening a terminal and then running this command. 

However, it would be great if this command could launch automatically in the background when wanting to play a video with mpv by using this extension. 

Is this somehow possible?

Thanks! :)

**Comment by Thann** [comment]
What OS are you using?

**Comment by orschiro** [comment]
I am Fedora 27 GNOME right now.

**Comment by Thann** [comment]
Cool, you can use the graphical "Gnome Tweak Tool" to edit your autostart apps.

Or you can just paste this into your term: `cp ~/.local/share/applications/Play\ With\ MPV\ \(server\).desktop ~/.config/autostart`

I'll add these instructions to the README =]

**Comment by orschiro** [comment]
Great, thanks! :-) Is it on purpose that the desktop file is green (executable?) and has these ''?

![screenshot from 2018-02-07 08-52-56](https://user-images.githubusercontent.com/170947/35904691-60ee8eb6-0be4-11e8-95bd-e746bd846d69.png)

**Comment by Thann** [comment]
These things you've noticed are not necessarily problems, but probably could be improved.
I'm using the python module install_freedesktop which has all of these quirks, I've thought about contributing some of these changes to that project, but if you want to, I could help you. =]

All the code is here:
https://github.com/welshjf/install_freedesktop/blob/master/install_freedesktop.py

**Comment by orschiro** [comment]
>  but if you want to, I could help you. =]

Yes, please! Eager to contribute. :-)

**Comment by Thann** [comment]
Sorry, I was doing research and trying to make a write up to help you, but it was getting hard to explain, so I just went ahead and did it, but I don't want to take all the fun away, so I'll explain anyway, and you can try to fix it yourself, and send them a PR if you want =] 

1. What was wrong
  a. desktop filename was not configurable, and has a standard
  b. file was executable for no reason
2. Where I found the info
  a. https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#file-naming
  b. https://unix.stackexchange.com/questions/373239/what-is-the-advantage-of-desktop-files-without-executable-bit-set
3. What the fixes should look like
  a. The filename can be anything, but _should_ be configurable and standardized.
    - In my setup.py, I should be able to set the filename, and the installer should warn if it's non-standard
  b. The file should request to be executed by `xdg-open`
4. How to contribute upstream
  - You should fork the install_desktop repo
  - Make and commit your changes
  - Open a Pull Request

Go ahead and give it a try if you want, and if you get stuck feel free to comment on this issue, or take a peek at my solution on my github.  
Also, as you probably know, trying to get your changes merged into the upstream project is the hardest part of opensource development, so LMK if you want to do that =]

**Comment by orschiro** [comment]
> Sorry, I was doing research and trying to make a write up to help you, but it was getting hard to explain, so I just went ahead and did it, but I don't want to take all the fun away, so I'll explain anyway, and you can try to fix it yourself, and send them a PR if you want =]

Wow, great instructions! Let me see if I can follow them tomorrow. Thanks :-)

**Comment by orschiro** [comment]
Sorry @Thann, currently busy with other stuff and don't find the time to contribute upstream!

**Comment by Thann** [comment]
No worries dude, thanks for pointing out so many issues =]
