### ISSUE TITLE
Provided pip install command fails

### ISSUE THREAD

**Issue by bwat47** [Thann/play-with-mpv#8]
If I run the install command from the readme it's failing:

brandon@xps13 ~ $ pip install git+git://github.com/thann/play-with-mpv --user
Collecting git+git://github.com/thann/play-with-mpv
  Cloning git://github.com/thann/play-with-mpv to /tmp/pip-uC2Hk3-build
    Complete output from command python setup.py egg_info:
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.

Tried it on two different machines and got the same result

I tried manually cloning the repo (git clone git://github.com/thann/play-with-mpv) and that works without error. I then tried pip install /path/to/play-with-mpv --user and that failed with the same user as above

**Comment by bwat47** [comment]
I got it to work by cloning the repo and then editing the setup.py file to remove this section:

+    dependency_links=[
+        "git+ssh://git@github.com/thann/install_freedesktop.git@master#egg=install_freedesktop-0.2.0"
+    ],

**Comment by Thann** [comment]
damn, thanks for the heads up

**Comment by Thann** [comment]
This is because I used an ssh url for that lib. Can you confirm this is fixed with the latest update?

Also please ensure that `ls ~/.local/share/applications/thann.play-with-mpv.desktop` exists =]

**Comment by bwat47** [comment]
Yes it works without error now, and the .desktop file is there :)

**Comment by Thann** [comment]
Awesome! Thanks for finding and debugging this for me =]
